INSERT INTO ARTISTS(ARTIST_NAME) VALUES('Queen');
INSERT INTO ARTISTS(ARTIST_NAME) VALUES('Metallica');
INSERT INTO ARTISTS(ARTIST_NAME) VALUES('Eluveitie');
INSERT INTO ARTISTS(ARTIST_NAME) VALUES('Ariana Grande');
INSERT INTO ARTISTS(ARTIST_NAME) VALUES('2Pac');
INSERT INTO ARTISTS(ARTIST_NAME) VALUES('Ine Kafe');
INSERT INTO ARTISTS(ARTIST_NAME) VALUES('Korn');
INSERT INTO ARTISTS(ARTIST_NAME) VALUES('Kontrafakt');

INSERT INTO GENRES(GENRE_TYPES) VALUES('RAP');
INSERT INTO GENRES(GENRE_TYPES) VALUES('ROCK');
INSERT INTO GENRES(GENRE_TYPES) VALUES('FOLK_METAL');
INSERT INTO GENRES(GENRE_TYPES) VALUES('ALTERNATIVE_METAL');
INSERT INTO GENRES(GENRE_TYPES) VALUES('HARD_ROCK');
INSERT INTO GENRES(GENRE_TYPES) VALUES('EPIC_MUSIC');

INSERT INTO PLAYLISTS(PLAYLIST_NAME, RATING) VALUES('Road_classic', 'GOOD');
INSERT INTO PLAYLISTS(PLAYLIST_NAME, RATING) VALUES('Rappin_for_Jesus', 'STANDARD');
INSERT INTO PLAYLISTS(PLAYLIST_NAME, RATING) VALUES('Metal_Blast', 'EPIC');
INSERT INTO PLAYLISTS(PLAYLIST_NAME, RATING) VALUES('Mix_of_Pix', 'LEGENDARY');

INSERT INTO TRACKS(TRACK_FORMAT, TRACK_LENGTH, TRACK_NAME, TRACK_YEAR) VALUES('.mp3', 4.15, 'Rose_for_Epona', 2004);
INSERT INTO TRACKS(TRACK_FORMAT, TRACK_LENGTH, TRACK_NAME, TRACK_YEAR) VALUES('.mp3', 3.23, 'Nothing_else_Matters', 1989);
INSERT INTO TRACKS(TRACK_FORMAT, TRACK_LENGTH, TRACK_NAME, TRACK_YEAR) VALUES('.flack', 7.10, 'We_will_rock_You', 1998);
INSERT INTO TRACKS(TRACK_FORMAT, TRACK_LENGTH, TRACK_NAME, TRACK_YEAR) VALUES('.mp4', 5.0, 'Straight_outta_Compton', 2002);
INSERT INTO TRACKS(TRACK_FORMAT, TRACK_LENGTH, TRACK_NAME, TRACK_YEAR) VALUES('.mp3', 3.45, 'Zaverecna', 2006);
INSERT INTO TRACKS(TRACK_FORMAT, TRACK_LENGTH, TRACK_NAME, TRACK_YEAR) VALUES('.mp4', 5.20, 'Avalanche', 2019);

